# yamllint disable rule:line-length rule:truthy
---
name: Associate Service

on:
  workflow_dispatch:
    inputs:
      environment_identifier:
        description: 'Environment identifier (<product_identifier>_<environment>_<location> in lower case)'
        required: true
      service_identifier:
        description: 'Service identifier'
        required: true
      github_repo:
        description: 'GitHub repository (org/repo)'
        required: true
      port_run_id:
        description: 'Port action run id'
        required: true
      request_identifier:
        description: 'Request identifier that triggered this workflow'
        required: true

jobs:
  associate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURECLIENTID }}
      ARM_TENANT_ID: ${{ secrets.AZURETENANTID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURESUBSCRIPTIONID }}
      PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
      PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
      TF_VAR_environment_file: ${{ github.workspace }}/environments/${{ inputs.environment_identifier }}.yaml
      PORT_RUN_ID: ${{ inputs.port_run_id }}
      TF_VAR_port_run_id: ${{ inputs.port_run_id }}
    steps:
      - name: Log start associate
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ env.PORT_RUN_ID }}
          logMessage: 'Associating service ${{ inputs.service_identifier }} with ${{ inputs.environment_identifier }} using repo ${{ inputs.github_repo }}'

      - uses: actions/checkout@v5

      - name: Load environment context
        run: |
          ENV_FILE=environments/${{ inputs.environment_identifier }}.yaml
          if [ ! -f "$ENV_FILE" ]; then
            echo "Environment file not found" >&2
            exit 1
          fi
          PRODUCT_IDENTIFIER=$(grep '^product_identifier:' "$ENV_FILE" | awk '{print $2}')
          ENVIRONMENT=$(grep '^environment:' "$ENV_FILE" | awk '{print $2}')
          LOCATION=$(grep '^location:' "$ENV_FILE" | awk '{print $2}')
          ENV_SHORT_NAME=$(grep '^environment_short_name:' "$ENV_FILE" | awk '{print $2}')
          echo "PRODUCT_IDENTIFIER=$PRODUCT_IDENTIFIER" >> $GITHUB_ENV
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "LOCATION=$LOCATION" >> $GITHUB_ENV
          echo "ENV_SHORT_NAME=$ENV_SHORT_NAME" >> $GITHUB_ENV

      - name: Set storage container name
        run: |
          CONTAINER_NAME=$(echo "${ENV_SHORT_NAME}${ENVIRONMENT}${LOCATION}" | tr '[:upper:]' '[:lower:]' | tr ' _' '-')
          echo "CONTAINER_NAME=$CONTAINER_NAME" >> $GITHUB_ENV

      - name: Update services list
        run: |
          pip install pyyaml
          cat <<'PY' > update_service.py
            import yaml, os
            env_file = os.environ['ENV_FILE']
            service_id = os.environ['SERVICE_ID']
            github_repo = os.environ['GITHUB_REPO']
            port_run_id = os.environ['PORT_RUN_ID']
            with open(env_file) as f:
                data = yaml.safe_load(f) or {}
            services = data.get('services', [])
            for svc in services:
                if svc.get('service_identifier') == service_id:
                    svc['github'] = {'repository': github_repo}
                    break
            else:
                services.append({'service_identifier': service_id, 'github': {'repository': github_repo}})
            data['services'] = services
            data['port_run_id'] = port_run_id
            with open(env_file, 'w') as f:
                yaml.dump(data, f, sort_keys=False)
          PY
          sed -i 's/^ *//' update_service.py
          python update_service.py
        env:
          ENV_FILE: ${{ github.workspace }}/environments/${{ inputs.environment_identifier }}.yaml
          SERVICE_ID: ${{ inputs.service_identifier }}
          GITHUB_REPO: ${{ inputs.github_repo }}

      - name: Commit updated environment file
        run: |
          git config user.email "75343302+getport-io[bot]@users.noreply.github.com"
          git config user.name "getport-io[bot]"
          git add environments/${{ inputs.environment_identifier }}.yaml
          git commit -m "Associate service ${{ inputs.service_identifier }} with ${{ inputs.environment_identifier }}"
          git push origin HEAD:main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURECLIENTID }}
          tenant-id: ${{ secrets.AZURETENANTID }}
          subscription-id: ${{ secrets.AZURESUBSCRIPTIONID }}

      - name: Terraform Init
        run: |
          terraform -chdir=terraform init \
            -backend-config="resource_group_name=v1vhm-rg-vending-prod-uks-001" \
            -backend-config="storage_account_name=vendingtfstate" \
            -backend-config="container_name=${CONTAINER_NAME}" \
            -backend-config="key=${PRODUCT_IDENTIFIER}_${ENVIRONMENT}_${LOCATION}.tfstate" \
            -reconfigure

      - name: Terraform Plan
        id: plan
        run: |
          set +e
          terraform -chdir=terraform plan -no-color 2>&1 | tee plan.log
          status=$?
          echo "log<<EOF" >> $GITHUB_OUTPUT
          cat plan.log >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          exit $status

      - name: Terraform Apply (update Port relations)
        id: apply
        run: |
          set +e
          terraform -chdir=terraform apply -auto-approve -no-color 2>&1 | tee apply.log
          status=$?
          echo "log<<EOF" >> $GITHUB_OUTPUT
          cat apply.log >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          exit $status

      - name: Update request status
        if: success()
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: UPSERT
          blueprint: request
          identifier: ${{ inputs.request_identifier }}
          properties: >-
            {"status": "Configuring Service"}

      - name: Log association complete
        if: success()
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ env.PORT_RUN_ID }}
          logMessage: 'Service association complete for ${{ inputs.service_identifier }} in ${{ inputs.environment_identifier }}'

      - name: Log association failure
        if: failure()
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ env.PORT_RUN_ID }}
          status: FAILURE
          logMessage: "Associate stage failed: plan=${{ steps.plan.outputs.log }} apply=${{ steps.apply.outputs.log }}"
